
name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: package_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create Git Tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git tag -a v${{ steps.package_version.outputs.current-version}} -m "Release v${{ steps.package_version.outputs.current-version }}"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
