
name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: package_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create Git Tag
        id: create_tag
        run: |
          TAG_NAME="v${{ steps.package_version.outputs.current-version}}"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Creating tag $TAG_NAME"
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
            git push origin --tags
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
